version: '3.1'
services: 
  web:
    restart: always
    build: .
    container_name: fbk-web
    volumes: 
      - ./:/var/www/
    depends_on: 
      - db
      
  db:
    image: postgres
    restart: always
    container_name: fbk-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: fbk.user
      POSTGRES_PASSWORD: fbk.user123
      POSTGRES_DB: fbk.arquivo.dbdata
    volumes: 
    - "./.docker/dbdata:/var/lib/postgresql/data"

  nginx:
    build: ./.docker/nginx
    restart: always
    container_name: fbk-nginx
    ports:
      - "8000:80"
    volumes: 
      - ./:/var/www
    depends_on: 
      - web


  

